file1 = open("TFWA.txt","r+")
position = file1.tell()
print(position)
str1 = file1.read(10)
position = file1.tell()
print(str1)
print(position)
file1.seek(1,0)
str1 = file1.read(9)
position = file1.tell()
print(str1)
print(position)
file1.close()